package ca.uhn.example.mybatis;

import java.util.Date;

public class MyPatient {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_id
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_family_ide
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_family_ide;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_given_ide
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_given_ide;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_family_syl
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_family_syl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_given_syl
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_given_syl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_family_abc
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_family_abc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_given_abc
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_given_abc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_gender
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_birthdate
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private Date pt_birthdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_phone
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_zip
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_zip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_patient.pt_address
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	private String pt_address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_id
	 * @return  the value of public.my_patient.pt_id
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_id() {
		return pt_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_id
	 * @param pt_id  the value for public.my_patient.pt_id
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_id(String pt_id) {
		this.pt_id = pt_id == null ? null : pt_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_family_ide
	 * @return  the value of public.my_patient.pt_family_ide
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_family_ide() {
		return pt_family_ide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_family_ide
	 * @param pt_family_ide  the value for public.my_patient.pt_family_ide
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_family_ide(String pt_family_ide) {
		this.pt_family_ide = pt_family_ide == null ? null : pt_family_ide.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_given_ide
	 * @return  the value of public.my_patient.pt_given_ide
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_given_ide() {
		return pt_given_ide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_given_ide
	 * @param pt_given_ide  the value for public.my_patient.pt_given_ide
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_given_ide(String pt_given_ide) {
		this.pt_given_ide = pt_given_ide == null ? null : pt_given_ide.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_family_syl
	 * @return  the value of public.my_patient.pt_family_syl
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_family_syl() {
		return pt_family_syl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_family_syl
	 * @param pt_family_syl  the value for public.my_patient.pt_family_syl
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_family_syl(String pt_family_syl) {
		this.pt_family_syl = pt_family_syl == null ? null : pt_family_syl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_given_syl
	 * @return  the value of public.my_patient.pt_given_syl
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_given_syl() {
		return pt_given_syl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_given_syl
	 * @param pt_given_syl  the value for public.my_patient.pt_given_syl
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_given_syl(String pt_given_syl) {
		this.pt_given_syl = pt_given_syl == null ? null : pt_given_syl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_family_abc
	 * @return  the value of public.my_patient.pt_family_abc
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_family_abc() {
		return pt_family_abc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_family_abc
	 * @param pt_family_abc  the value for public.my_patient.pt_family_abc
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_family_abc(String pt_family_abc) {
		this.pt_family_abc = pt_family_abc == null ? null : pt_family_abc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_given_abc
	 * @return  the value of public.my_patient.pt_given_abc
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_given_abc() {
		return pt_given_abc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_given_abc
	 * @param pt_given_abc  the value for public.my_patient.pt_given_abc
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_given_abc(String pt_given_abc) {
		this.pt_given_abc = pt_given_abc == null ? null : pt_given_abc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_gender
	 * @return  the value of public.my_patient.pt_gender
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_gender() {
		return pt_gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_gender
	 * @param pt_gender  the value for public.my_patient.pt_gender
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_gender(String pt_gender) {
		this.pt_gender = pt_gender == null ? null : pt_gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_birthdate
	 * @return  the value of public.my_patient.pt_birthdate
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public Date getPt_birthdate() {
		return pt_birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_birthdate
	 * @param pt_birthdate  the value for public.my_patient.pt_birthdate
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_birthdate(Date pt_birthdate) {
		this.pt_birthdate = pt_birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_phone
	 * @return  the value of public.my_patient.pt_phone
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_phone() {
		return pt_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_phone
	 * @param pt_phone  the value for public.my_patient.pt_phone
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_phone(String pt_phone) {
		this.pt_phone = pt_phone == null ? null : pt_phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_zip
	 * @return  the value of public.my_patient.pt_zip
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_zip() {
		return pt_zip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_zip
	 * @param pt_zip  the value for public.my_patient.pt_zip
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_zip(String pt_zip) {
		this.pt_zip = pt_zip == null ? null : pt_zip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_patient.pt_address
	 * @return  the value of public.my_patient.pt_address
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getPt_address() {
		return pt_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_patient.pt_address
	 * @param pt_address  the value for public.my_patient.pt_address
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setPt_address(String pt_address) {
		this.pt_address = pt_address == null ? null : pt_address.trim();
	}
}