package ca.uhn.example.mybatis;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MyPatientExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public MyPatientExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andPt_idIsNull() {
			addCriterion("pt_id is null");
			return (Criteria) this;
		}

		public Criteria andPt_idIsNotNull() {
			addCriterion("pt_id is not null");
			return (Criteria) this;
		}

		public Criteria andPt_idEqualTo(String value) {
			addCriterion("pt_id =", value, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idNotEqualTo(String value) {
			addCriterion("pt_id <>", value, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idGreaterThan(String value) {
			addCriterion("pt_id >", value, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idGreaterThanOrEqualTo(String value) {
			addCriterion("pt_id >=", value, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idLessThan(String value) {
			addCriterion("pt_id <", value, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idLessThanOrEqualTo(String value) {
			addCriterion("pt_id <=", value, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idLike(String value) {
			addCriterion("pt_id like", value, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idNotLike(String value) {
			addCriterion("pt_id not like", value, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idIn(List<String> values) {
			addCriterion("pt_id in", values, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idNotIn(List<String> values) {
			addCriterion("pt_id not in", values, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idBetween(String value1, String value2) {
			addCriterion("pt_id between", value1, value2, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_idNotBetween(String value1, String value2) {
			addCriterion("pt_id not between", value1, value2, "pt_id");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideIsNull() {
			addCriterion("pt_family_ide is null");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideIsNotNull() {
			addCriterion("pt_family_ide is not null");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideEqualTo(String value) {
			addCriterion("pt_family_ide =", value, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideNotEqualTo(String value) {
			addCriterion("pt_family_ide <>", value, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideGreaterThan(String value) {
			addCriterion("pt_family_ide >", value, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideGreaterThanOrEqualTo(String value) {
			addCriterion("pt_family_ide >=", value, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideLessThan(String value) {
			addCriterion("pt_family_ide <", value, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideLessThanOrEqualTo(String value) {
			addCriterion("pt_family_ide <=", value, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideLike(String value) {
			addCriterion("pt_family_ide like", value, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideNotLike(String value) {
			addCriterion("pt_family_ide not like", value, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideIn(List<String> values) {
			addCriterion("pt_family_ide in", values, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideNotIn(List<String> values) {
			addCriterion("pt_family_ide not in", values, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideBetween(String value1, String value2) {
			addCriterion("pt_family_ide between", value1, value2, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_ideNotBetween(String value1, String value2) {
			addCriterion("pt_family_ide not between", value1, value2, "pt_family_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideIsNull() {
			addCriterion("pt_given_ide is null");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideIsNotNull() {
			addCriterion("pt_given_ide is not null");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideEqualTo(String value) {
			addCriterion("pt_given_ide =", value, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideNotEqualTo(String value) {
			addCriterion("pt_given_ide <>", value, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideGreaterThan(String value) {
			addCriterion("pt_given_ide >", value, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideGreaterThanOrEqualTo(String value) {
			addCriterion("pt_given_ide >=", value, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideLessThan(String value) {
			addCriterion("pt_given_ide <", value, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideLessThanOrEqualTo(String value) {
			addCriterion("pt_given_ide <=", value, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideLike(String value) {
			addCriterion("pt_given_ide like", value, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideNotLike(String value) {
			addCriterion("pt_given_ide not like", value, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideIn(List<String> values) {
			addCriterion("pt_given_ide in", values, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideNotIn(List<String> values) {
			addCriterion("pt_given_ide not in", values, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideBetween(String value1, String value2) {
			addCriterion("pt_given_ide between", value1, value2, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_given_ideNotBetween(String value1, String value2) {
			addCriterion("pt_given_ide not between", value1, value2, "pt_given_ide");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylIsNull() {
			addCriterion("pt_family_syl is null");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylIsNotNull() {
			addCriterion("pt_family_syl is not null");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylEqualTo(String value) {
			addCriterion("pt_family_syl =", value, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylNotEqualTo(String value) {
			addCriterion("pt_family_syl <>", value, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylGreaterThan(String value) {
			addCriterion("pt_family_syl >", value, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylGreaterThanOrEqualTo(String value) {
			addCriterion("pt_family_syl >=", value, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylLessThan(String value) {
			addCriterion("pt_family_syl <", value, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylLessThanOrEqualTo(String value) {
			addCriterion("pt_family_syl <=", value, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylLike(String value) {
			addCriterion("pt_family_syl like", value, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylNotLike(String value) {
			addCriterion("pt_family_syl not like", value, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylIn(List<String> values) {
			addCriterion("pt_family_syl in", values, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylNotIn(List<String> values) {
			addCriterion("pt_family_syl not in", values, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylBetween(String value1, String value2) {
			addCriterion("pt_family_syl between", value1, value2, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_sylNotBetween(String value1, String value2) {
			addCriterion("pt_family_syl not between", value1, value2, "pt_family_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylIsNull() {
			addCriterion("pt_given_syl is null");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylIsNotNull() {
			addCriterion("pt_given_syl is not null");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylEqualTo(String value) {
			addCriterion("pt_given_syl =", value, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylNotEqualTo(String value) {
			addCriterion("pt_given_syl <>", value, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylGreaterThan(String value) {
			addCriterion("pt_given_syl >", value, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylGreaterThanOrEqualTo(String value) {
			addCriterion("pt_given_syl >=", value, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylLessThan(String value) {
			addCriterion("pt_given_syl <", value, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylLessThanOrEqualTo(String value) {
			addCriterion("pt_given_syl <=", value, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylLike(String value) {
			addCriterion("pt_given_syl like", value, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylNotLike(String value) {
			addCriterion("pt_given_syl not like", value, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylIn(List<String> values) {
			addCriterion("pt_given_syl in", values, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylNotIn(List<String> values) {
			addCriterion("pt_given_syl not in", values, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylBetween(String value1, String value2) {
			addCriterion("pt_given_syl between", value1, value2, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_given_sylNotBetween(String value1, String value2) {
			addCriterion("pt_given_syl not between", value1, value2, "pt_given_syl");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcIsNull() {
			addCriterion("pt_family_abc is null");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcIsNotNull() {
			addCriterion("pt_family_abc is not null");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcEqualTo(String value) {
			addCriterion("pt_family_abc =", value, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcNotEqualTo(String value) {
			addCriterion("pt_family_abc <>", value, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcGreaterThan(String value) {
			addCriterion("pt_family_abc >", value, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcGreaterThanOrEqualTo(String value) {
			addCriterion("pt_family_abc >=", value, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcLessThan(String value) {
			addCriterion("pt_family_abc <", value, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcLessThanOrEqualTo(String value) {
			addCriterion("pt_family_abc <=", value, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcLike(String value) {
			addCriterion("pt_family_abc like", value, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcNotLike(String value) {
			addCriterion("pt_family_abc not like", value, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcIn(List<String> values) {
			addCriterion("pt_family_abc in", values, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcNotIn(List<String> values) {
			addCriterion("pt_family_abc not in", values, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcBetween(String value1, String value2) {
			addCriterion("pt_family_abc between", value1, value2, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_family_abcNotBetween(String value1, String value2) {
			addCriterion("pt_family_abc not between", value1, value2, "pt_family_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcIsNull() {
			addCriterion("pt_given_abc is null");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcIsNotNull() {
			addCriterion("pt_given_abc is not null");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcEqualTo(String value) {
			addCriterion("pt_given_abc =", value, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcNotEqualTo(String value) {
			addCriterion("pt_given_abc <>", value, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcGreaterThan(String value) {
			addCriterion("pt_given_abc >", value, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcGreaterThanOrEqualTo(String value) {
			addCriterion("pt_given_abc >=", value, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcLessThan(String value) {
			addCriterion("pt_given_abc <", value, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcLessThanOrEqualTo(String value) {
			addCriterion("pt_given_abc <=", value, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcLike(String value) {
			addCriterion("pt_given_abc like", value, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcNotLike(String value) {
			addCriterion("pt_given_abc not like", value, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcIn(List<String> values) {
			addCriterion("pt_given_abc in", values, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcNotIn(List<String> values) {
			addCriterion("pt_given_abc not in", values, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcBetween(String value1, String value2) {
			addCriterion("pt_given_abc between", value1, value2, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_given_abcNotBetween(String value1, String value2) {
			addCriterion("pt_given_abc not between", value1, value2, "pt_given_abc");
			return (Criteria) this;
		}

		public Criteria andPt_genderIsNull() {
			addCriterion("pt_gender is null");
			return (Criteria) this;
		}

		public Criteria andPt_genderIsNotNull() {
			addCriterion("pt_gender is not null");
			return (Criteria) this;
		}

		public Criteria andPt_genderEqualTo(String value) {
			addCriterion("pt_gender =", value, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderNotEqualTo(String value) {
			addCriterion("pt_gender <>", value, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderGreaterThan(String value) {
			addCriterion("pt_gender >", value, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderGreaterThanOrEqualTo(String value) {
			addCriterion("pt_gender >=", value, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderLessThan(String value) {
			addCriterion("pt_gender <", value, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderLessThanOrEqualTo(String value) {
			addCriterion("pt_gender <=", value, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderLike(String value) {
			addCriterion("pt_gender like", value, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderNotLike(String value) {
			addCriterion("pt_gender not like", value, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderIn(List<String> values) {
			addCriterion("pt_gender in", values, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderNotIn(List<String> values) {
			addCriterion("pt_gender not in", values, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderBetween(String value1, String value2) {
			addCriterion("pt_gender between", value1, value2, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_genderNotBetween(String value1, String value2) {
			addCriterion("pt_gender not between", value1, value2, "pt_gender");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateIsNull() {
			addCriterion("pt_birthdate is null");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateIsNotNull() {
			addCriterion("pt_birthdate is not null");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateEqualTo(Date value) {
			addCriterionForJDBCDate("pt_birthdate =", value, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateNotEqualTo(Date value) {
			addCriterionForJDBCDate("pt_birthdate <>", value, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateGreaterThan(Date value) {
			addCriterionForJDBCDate("pt_birthdate >", value, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("pt_birthdate >=", value, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateLessThan(Date value) {
			addCriterionForJDBCDate("pt_birthdate <", value, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("pt_birthdate <=", value, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateIn(List<Date> values) {
			addCriterionForJDBCDate("pt_birthdate in", values, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateNotIn(List<Date> values) {
			addCriterionForJDBCDate("pt_birthdate not in", values, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("pt_birthdate between", value1, value2, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_birthdateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("pt_birthdate not between", value1, value2, "pt_birthdate");
			return (Criteria) this;
		}

		public Criteria andPt_phoneIsNull() {
			addCriterion("pt_phone is null");
			return (Criteria) this;
		}

		public Criteria andPt_phoneIsNotNull() {
			addCriterion("pt_phone is not null");
			return (Criteria) this;
		}

		public Criteria andPt_phoneEqualTo(String value) {
			addCriterion("pt_phone =", value, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneNotEqualTo(String value) {
			addCriterion("pt_phone <>", value, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneGreaterThan(String value) {
			addCriterion("pt_phone >", value, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneGreaterThanOrEqualTo(String value) {
			addCriterion("pt_phone >=", value, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneLessThan(String value) {
			addCriterion("pt_phone <", value, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneLessThanOrEqualTo(String value) {
			addCriterion("pt_phone <=", value, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneLike(String value) {
			addCriterion("pt_phone like", value, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneNotLike(String value) {
			addCriterion("pt_phone not like", value, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneIn(List<String> values) {
			addCriterion("pt_phone in", values, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneNotIn(List<String> values) {
			addCriterion("pt_phone not in", values, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneBetween(String value1, String value2) {
			addCriterion("pt_phone between", value1, value2, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_phoneNotBetween(String value1, String value2) {
			addCriterion("pt_phone not between", value1, value2, "pt_phone");
			return (Criteria) this;
		}

		public Criteria andPt_zipIsNull() {
			addCriterion("pt_zip is null");
			return (Criteria) this;
		}

		public Criteria andPt_zipIsNotNull() {
			addCriterion("pt_zip is not null");
			return (Criteria) this;
		}

		public Criteria andPt_zipEqualTo(String value) {
			addCriterion("pt_zip =", value, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipNotEqualTo(String value) {
			addCriterion("pt_zip <>", value, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipGreaterThan(String value) {
			addCriterion("pt_zip >", value, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipGreaterThanOrEqualTo(String value) {
			addCriterion("pt_zip >=", value, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipLessThan(String value) {
			addCriterion("pt_zip <", value, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipLessThanOrEqualTo(String value) {
			addCriterion("pt_zip <=", value, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipLike(String value) {
			addCriterion("pt_zip like", value, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipNotLike(String value) {
			addCriterion("pt_zip not like", value, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipIn(List<String> values) {
			addCriterion("pt_zip in", values, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipNotIn(List<String> values) {
			addCriterion("pt_zip not in", values, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipBetween(String value1, String value2) {
			addCriterion("pt_zip between", value1, value2, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_zipNotBetween(String value1, String value2) {
			addCriterion("pt_zip not between", value1, value2, "pt_zip");
			return (Criteria) this;
		}

		public Criteria andPt_addressIsNull() {
			addCriterion("pt_address is null");
			return (Criteria) this;
		}

		public Criteria andPt_addressIsNotNull() {
			addCriterion("pt_address is not null");
			return (Criteria) this;
		}

		public Criteria andPt_addressEqualTo(String value) {
			addCriterion("pt_address =", value, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressNotEqualTo(String value) {
			addCriterion("pt_address <>", value, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressGreaterThan(String value) {
			addCriterion("pt_address >", value, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressGreaterThanOrEqualTo(String value) {
			addCriterion("pt_address >=", value, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressLessThan(String value) {
			addCriterion("pt_address <", value, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressLessThanOrEqualTo(String value) {
			addCriterion("pt_address <=", value, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressLike(String value) {
			addCriterion("pt_address like", value, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressNotLike(String value) {
			addCriterion("pt_address not like", value, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressIn(List<String> values) {
			addCriterion("pt_address in", values, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressNotIn(List<String> values) {
			addCriterion("pt_address not in", values, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressBetween(String value1, String value2) {
			addCriterion("pt_address between", value1, value2, "pt_address");
			return (Criteria) this;
		}

		public Criteria andPt_addressNotBetween(String value1, String value2) {
			addCriterion("pt_address not between", value1, value2, "pt_address");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.my_patient
	 * @mbg.generated  Fri May 05 17:26:35 JST 2023
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.my_patient
     *
     * @mbg.generated do_not_delete_during_merge Fri May 05 17:25:08 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}