DROP TABLE IF EXISTS MY_PATIENT;
CREATE TABLE MY_PATIENT (
    PT_ID CHAR(10) NOT NULL,
    PT_FAMILY_IDE CHAR(20) NOT NULL,
    PT_GIVEN_IDE CHAR(20) NOT NULL,
    PT_FAMILY_SYL CHAR(20) NOT NULL,
    PT_GIVEN_SYL CHAR(20) NOT NULL,
    PT_FAMILY_ABC CHAR(20) NOT NULL,
    PT_GIVEN_ABC CHAR(20) NOT NULL,
    PT_GENDER CHAR(1) NOT NULL,
    PT_BIRTHDATE DATE NOT NULL,
    PT_PHONE CHAR(20) NOT NULL,
    PT_ZIP CHAR(10) NOT NULL,
    PT_ADDRESS CHAR (64) NULL,
    PRIMARY KEY (
       PT_ID
    )
);

\COPY MY_PATIENT FROM ./MY_PATIENT.csv WITH CSV;
